import Head from 'next/head';
import Form from '../Components/Form';
import Members from '../Components/Members';

export default function Home({ user }) {
  return (
    <div className="">
      <Head>
        <title>Members</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:flex gap-4">
        <Form />
        <Members data={user} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch('http://localhost:3000/api/');
  const data = await res.json();
  return {
    props: {
      user: data.data,
    },
  };
};
